### ISSUE TITLE
Odd stack trace in deployment logs

### ISSUE THREAD

**Issue by mike-rogers** [swanson/stringer#368]
On a 'successful' deploy (I haven't played around with the app to verify, but it comes up and accepted a password) I found the following in the Heroku logs:

```
Writing config/database.yml to read from DATABASE_URL
       Could not detect rake tasks
       ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
       and using the production group of your Gemfile.
       This may be intentional, if you expected rake tasks to be run
       cancel the build (CTRL+C) and fix the error then commit the fix:
       rake aborted!
       Invalid DATABASE_URL
       (erb):9:in `rescue in <main>'
       (erb):6:in `<main>'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/ruby-2.0.0/lib/ruby/2.0.0/erb.rb:849:in `eval'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/ruby-2.0.0/lib/ruby/2.0.0/erb.rb:849:in `result'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/sinatra-activerecord-1.2.3/lib/sinatra/activerecord.rb:39:in `database_file='
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1208:in `set'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/sinatra-activerecord-1.2.3/lib/sinatra/activerecord.rb:50:in `registered'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1391:in `block in register'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1389:in `each'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1389:in `register'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/app.rb:22:in `<class:Stringer>'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/app.rb:18:in `<top (required)>'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/Rakefile:12:in `<top (required)>'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
       /tmp/build_bbaa81cfd6200cb752ae0c269ba57bbc/swanson-stringer-4ab7ffc/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
       vendor/bundle/bin/rake:16:in `load'
       vendor/bundle/bin/rake:16:in `<main>'
```

I'm not actually sure if it's a problem.

**Comment by Koronen** [comment]
If this error occurs on the instance you tried to deploy in #367, I suspect it's because your app doesn't have the PostgreSQL addon attached. This, in turn, because we don't currently specify that dependency in `app.json`. I'll fix that.
