### ISSUE TITLE
undefined method `gsub' for nil:NilClass during migration

### ISSUE THREAD

**Issue by bitboxer** [swanson/stringer#373]
I just updated my stringer and got this while migrating:

```
undefined method `gsub' for nil:NilClass/home/bodo02/stringer/db/migrate/20141102103617_fix_invalid_titles_with_unicode_line_endings.rb:4:in `block in up'
/home/bodo02/.gem/gems/activerecord-4.0.13/lib/active_record/relation/batches.rb:26:in `block (2 levels) in find_each'
/home/bodo02/.gem/gems/activerecord-4.0.13/lib/active_record/relation/batches.rb:26:in `each'
/home/bodo02/.gem/gems/activerecord-4.0.13/lib/active_record/relation/batches.rb:26:in `block in find_each'
/home/bodo02/.gem/gems/activerecord-4.0.13/lib/active_record/relation/batches.rb:76:in `find_in_batches'
/home/bodo02/.gem/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:70:in `find_in_batches'
/home/bodo02/.gem/gems/activerecord-4.0.13/lib/active_record/relation/batches.rb:25:in `find_each'
/home/bodo02/.gem/gems/activerecord-4.0.13/lib/active_record/querying.rb:8:in `find_each'
/home/bodo02/stringer/db/migrate/20141102103617_fix_invalid_titles_with_unicode_line_endings.rb:3:in `up'
/
```

I had some story titles with nil in them, so the fix for me was to change the migration to this:

```
      valid_title = (story.title || "").gsub("\u2028", '').gsub("\u2029", '')
```

**Comment by swanson** [comment]
Thanks for the report.

I'd accept a PR that just skips the iteration if the title is nil if you (or someone else) wants to take care of it.
