### ISSUE TITLE
Migration to cedar-14 on heroku

### ISSUE THREAD

**Issue by nobuti** [swanson/stringer#384]
I was not able to complete the migration successfully, I had to rollback to a previous deploy. These are the logs:

```
Counting objects: 1, done.
Writing objects: 100% (1/1), 189 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rack
remote: -----> Using Ruby version: ruby-2.0.0
remote: -----> Installing dependencies using 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Rubygems 2.0.14 is not threadsafe, so your gems must be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
remote:        Using rake 10.1.1
remote:        Using i18n 0.6.9
remote:        Using minitest 4.7.5
remote:        Using multi_json 1.8.2
remote:        Using atomic 1.1.14
remote:        Using thread_safe 0.1.3
remote:        Using tzinfo 0.3.38
remote:        Using activesupport 4.0.2
remote:        Using builder 3.1.4
remote:        Using activemodel 4.0.2
remote:        Using activerecord-deprecated_finders 1.0.3
remote:        Using arel 4.0.1.20131022201058 from git://github.com/rails/arel.git (at 4-0-stable)
remote:        Using activerecord 4.0.2
remote:        Using backports 3.3.5
remote:        Using bcrypt-ruby 3.1.2
remote:        Using curb 0.8.5
remote:        Using delayed_job 4.0.0
remote:        Using delayed_job_active_record 4.0.0
remote:        Using excon 0.31.0
remote:        Using hpricot 0.8.6
remote:        Using feedbag 0.9.2
remote:        Using mini_portile 0.5.2
remote:        Using nokogiri 1.6.1
remote:        Using loofah 1.2.1.20130718080038 from git://github.com/swanson/loofah.git (at master)
remote:        Using sax-machine 0.2.1
remote:        Using feedjira 1.2.0
remote:        Using formatador 0.2.4
remote:        Using highline 1.6.20
remote:        Using jsmin 1.0.1
remote:        Using kgio 2.8.1
remote:        Using netrc 0.7.7
remote:        Using pg 0.17.1
remote:        Using rack 1.5.2
remote:        Using rack-protection 1.5.1
remote:        Using rack-test 0.6.2
remote:        Using racksh 1.0.0
remote:        Using raindrops 0.12.0
remote:        Using rendezvous 0.0.2
remote:        Using tilt 1.4.1
remote:        Using sinatra 1.4.4
remote:        Using sinatra-activerecord 1.2.3
remote:        Using sinatra-assetpack 0.3.1
remote:        Using sinatra-contrib 1.4.2
remote:        Using sinatra-flash 0.3.0
remote:        Using thread 0.1.3
remote:        Using unicorn 4.7.0
remote:        Using will_paginate 3.0.5
remote:        Using bundler 1.9.7
remote:        Bundle complete! 35 Gemfile dependencies, 48 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (0.64s)
remote:        Cleaning up the bundler cache.
remote: -----> Writing config/database.yml to read from DATABASE_URL
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        rake aborted!
remote:        Bad file descriptor - /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.1/io/open.rb
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.1/io/open.rb:2:in `close'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.1/io/open.rb:2:in `open'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.1/io/open.rb:2:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:22:in `block in require_relative_dir'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:21:in `each'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:21:in `require_relative_dir'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.1/io.rb:3:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:22:in `block in require_relative_dir'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:21:in `each'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:21:in `require_relative_dir'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.1.rb:3:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.2.rb:2:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.3.rb:2:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/1.9.rb:2:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/2.0.0.rb:2:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/2.0.rb:2:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports/tools.rb:328:in `require_with_backports'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/backports-3.3.5/lib/backports.rb:3:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/contrib/setup.rb:3:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/contrib.rb:1:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/contrib/all.rb:1:in `<top (required)>
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/app.rb:4:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/Rakefile:12:in `<top (required)>'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
remote:        /tmp/build_5153784be9481e7a57fb085d7f2bdf73/vendor/bundle/ruby/2.0.0/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
remote:        vendor/bundle/bin/rake:16:in `load'
remote:        vendor/bundle/bin/rake:16:in `<main>'
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> console, web
remote:        Default types for Ruby  -> rake
remote: 
remote: -----> Compressing... done, 31.2MB
remote: -----> Launching... done, v14
remote: Verifying deploy.... done.
```

**Comment by nobuti** [comment]
Rakefile missing. Updating the repo and push again resolves the issue.
