### ISSUE TITLE
Issue with one-click Heroku deploy

### ISSUE THREAD

**Issue by timbroder** [swanson/stringer#418]
Error on "Run scripts & scale dynos"

```
rake aborted!
Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 10.1.1. Prepending `bundle exec` to your command may solve this.
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:34:in `block in setup'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:19:in `setup'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler.rb:122:in `setup'
/app/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
```

Build log:

```
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.2.4
-----> Installing dependencies using bundler 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Installing i18n 0.6.11
       Installing rake 10.1.1
       Installing minitest 5.8.4
       Installing thread_safe 0.3.5
       Installing builder 3.2.2
       Installing arel 5.0.1.20140414130214
       Installing backports 3.6.1
       Installing json 1.8.3
       Installing bcrypt-ruby 3.1.2
       Installing mini_portile2 2.0.0
       Installing jsmin 1.0.1
       Installing curb 0.8.6
       Installing multi_json 1.11.2
       Installing kgio 2.9.3
       Installing rack 1.6.4
       Installing hpricot 0.8.6
       Installing tilt 1.4.1
       Installing thread 0.1.3
       Installing will_paginate 3.0.5
       Using bundler 1.9.7
       Installing tzinfo 1.2.2
       Installing pg 0.17.1
       Installing rack-protection 1.5.3
       Installing rack-ssl 1.4.1
       Installing rack-test 0.6.2
       Installing raindrops 0.13.0
       Installing feedbag 0.9.2
       Installing activesupport 4.1.14
       Installing sinatra 1.4.5
       Installing racksh 1.0.0
       Installing activemodel 4.1.14
       Installing delayed_job 4.1.1
       Installing sinatra-assetpack 0.3.1
       Installing sinatra-contrib 1.4.2
       Installing sinatra-flash 0.3.0
       Installing activerecord 4.1.14
       Installing delayed_job_active_record 4.1.0
       Installing sinatra-activerecord 1.2.3
       Installing nokogiri 1.6.7.2
       Installing sax-machine 0.2.1
       Installing loofah 2.0.0
       Installing feedjira 1.3.0
       Installing unicorn 4.7.0
       Bundle complete! 34 Gemfile dependencies, 43 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from sinatra-assetpack:
       ##################################################
       #  NOTE FOR UPGRADING FROM PRE-3.0.0 VERSION     #
       ##################################################
       Please note that sinatra-assetpack `img` helper method
       no more set the image width and height because this default
       behavior is not desirable with most recent CSS techniques
       regarding high resolutions images for "retina" displays
       ans "responsive" design CSS using for exemple width:100%.
       <img src="retina.jpg" width="1200" height="600">
       Is now simply this (unless you explicity set them) :
       <img src="retina.jpg">
       See https://github.com/rstacruz/sinatra-assetpack/pull/121
       Bundle completed (62.07s)
       Cleaning up the bundler cache.
###### WARNING:
       You have not declared a Ruby version in your Gemfile.
       To set your Ruby version add this line to your Gemfile:
       ruby '2.2.4'
       # See https://devcenter.heroku.com/articles/ruby-versions for more information.
-----> Discovering process types
       Procfile declares types     -> console, web
       Default types for buildpack -> rake
-----> Compressing...
       Done: 30.6M
-----> Launching...
       Released v6
       https://timstringer.herokuapp.com/ deployed to Heroku
```

Heroku [by hand](https://github.com/swanson/stringer/blob/master/docs/Heroku.md "by hand") works fine

**Comment by milligramme** [comment]
how to resolve this issue was shown in error message.
the fix was merged and now it will work fine.
