### ISSUE TITLE
Refuse to start

### ISSUE THREAD

**Issue by meradoou** [swanson/stringer#450]
Hello,
I installed Stringer on virtual machine with Archlinux https://github.com/swanson/stringer/blob/master/docs/VPS.md but It refused to start
```
[stringer@flotte stringer]$ foreman start
13:23:30 web.1     | started with pid 4170
13:23:30 console.1 | started with pid 4171
13:23:30 web.1     | I, [2017-04-11T13:23:30.524295 #4170]  INFO -- : Refreshing Gem list
13:23:32 web.1     | bundler: failed to load command: unicorn (/home/stringer/.rbenv/versions/2.3.3/bin/unicorn)
13:23:32 web.1     | Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
13:23:32 web.1     | Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
13:23:32 web.1     | Backtrace for gem load error is:
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/uglifier-3.0.2/lib/uglifier.rb:5:in `<top (required)>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
13:23:32 web.1     | config.ru:5:in `block in <main>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
13:23:32 web.1     | config.ru:1:in `new'
13:23:32 web.1     | config.ru:1:in `<main>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/bin/unicorn:22:in `load'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/bin/unicorn:22:in `<top (required)>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
13:23:32 web.1     | /home/stringer/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
13:23:32 web.1     | Bundler Error Backtrace:
13:23:32 web.1     | 
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
13:23:32 web.1     |   config.ru:5:in `block in <main>'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
13:23:32 web.1     |   config.ru:1:in `new'
13:23:32 web.1     |   config.ru:1:in `<main>'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/bin/unicorn:22:in `load'
13:23:32 web.1     |   /home/stringer/.rbenv/versions/2.3.3/bin/unicorn:22:in `<top (required)>'
13:23:32 console.1 | bundler: failed to load command: racksh (/home/stringer/.rbenv/versions/2.3.3/bin/racksh)
13:23:32 console.1 | Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
13:23:32 console.1 | Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
13:23:32 console.1 | Backtrace for gem load error is:
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/uglifier-3.0.2/lib/uglifier.rb:5:in `<top (required)>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
13:23:32 console.1 | config.ru:4:in `block in <main>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
13:23:32 console.1 | config.ru:in `new'
13:23:32 console.1 | config.ru:in `<main>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/racksh-1.0.0/lib/racksh/init.rb:23:in `init'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/racksh-1.0.0/bin/racksh:19:in `<top (required)>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/bin/racksh:22:in `load'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/bin/racksh:22:in `<top (required)>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
13:23:32 console.1 | /home/stringer/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
13:23:32 console.1 | Bundler Error Backtrace:
13:23:32 console.1 | 
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
13:23:32 console.1 |   config.ru:4:in `block in <main>'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
13:23:32 console.1 |   config.ru:in `new'
13:23:32 console.1 |   config.ru:in `<main>'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/racksh-1.0.0/lib/racksh/init.rb:23:in `init'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/racksh-1.0.0/bin/racksh:19:in `<top (required)>'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/bin/racksh:22:in `load'
13:23:32 console.1 |   /home/stringer/.rbenv/versions/2.3.3/bin/racksh:22:in `<top (required)>'
13:23:33 web.1     | exited with code 1
13:23:33 system    | sending SIGTERM to all processes
13:23:33 console.1 | exited with code 1
```

**Comment by Koronen** [comment]
I believe the following two lines are the interesting ones.
```
13:23:32 web.1     | Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
13:23:32 web.1     | Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```
This error is most likely related to https://github.com/swanson/stringer/pull/449.

What you need to do to fix this error is to install a Javascript runtime. I would suggest using the Node.js runtime, as it can be installed on your VM without requiring any changes to the Stringer codebase. For installation instructions, see https://nodejs.org/en/download/package-manager/#arch-linux.

PRs adding mentions of this new dependency to the docs would be much appreciated.

**Comment by meradoou** [comment]
Thank you. It works!
